# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_AMS <- function(model, n, t, p, r, sigma, S0, rho = NULL, rim = 0L, v0 = 0.04) {
    .Call(`_amsSim_simulate_AMS`, model, n, t, p, r, sigma, S0, rho, rim, v0)
}

AMS <- function(model, type, funz, n, t, p, r, sigma, S0, rho = NULL, rim = 0L, v0 = 0.04, Lmax = 0.0, strike = 1.0, K = 1L) {
    .Call(`_amsSim_AMS`, model, type, funz, n, t, p, r, sigma, S0, rho, rim, v0, Lmax, strike, K)
}

